### ISSUE TITLE
Sample source code not loaded on new file

### ISSUE THREAD

**Issue by davepagurek** [calder-gl/playground#36]
This is a regression I introduced where the default source code is only loaded in when the sample file is loaded, leaving other new files empty

**Comment by pbardea** [comment]
I can look into this today.

**Comment by davepagurek** [comment]
I made some changes in https://github.com/calder-gl/playground/pull/37, maybe check if this still happens now that it's merged

**Comment by pbardea** [comment]
Looks like the source code is auto-loaded on latest `master` on new files.
